language: csharp
dotnet: 3.1.401
sudo: required
mono: none
script:
- dotnet restore
- dotnet publish -c Release -o $TRAVIS_BUILD_DIR/out
- cp Dockerfile $TRAVIS_BUILD_DIR/out/Dockerfile
services: docker

before_install:
- openssl aes-256-cbc -K $encrypted_da7a7d6d72dd_key -iv $encrypted_da7a7d6d72dd_iv
  -in deployf_rsa.enc -out deployf_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deployf_rsa
- ssh-add ./deployf_rsa
addons:
  ssh_known_hosts: 165.227.158.125
before_deploy:
- eval "$(ssh-agent -s)"
- mkdir -p ~/.ssh && echo "Host *" > ~/.ssh/config && echo "StrictHostKeyChecking no" >> ~/.ssh/config
- chmod 600 deployf_rsa

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master 
