language: csharp
dotnet: 3.1.401
sudo: required
mono: none

script:
  - dotnet restore

  - dotnet build TshirtBackend.sln
services: docker
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x deploy.sh
  on:
    branch: master
  
